name: Java CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.9.0
        with:
          gradle-version: '8.5'
          build-root-directory: 'app'

      - name: Build project
        run: make build

      - name: Publish test coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: ${{github.workspace}}/app/src/main/java
        with:
          coverageCommand: make report
          coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
